---
abstract: 'Client library for GoodData REST-ful API'
author:
  - 'Lubomir Rintel <lkundrak@v3.sk>'
build_requires:
  JSON::XS: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-GoodData
provides:
  LWP::Authen::Gooddata:
    file: lib/LWP/Authen/Gooddata.pm
  WWW::GoodData:
    file: lib/WWW/GoodData.pm
  WWW::GoodData::Agent:
    file: lib/WWW/GoodData/Agent.pm
    version: 1.0
requires:
  Getopt::Long: 0
  IO::Socket::SSL: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Pod::Usage: 0
  Text::ParseWords: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-GoodData
  license: http://dev.perl.org/licenses/
  repository: https://github.com/lkundrak/www-gooddata
version: 1.4
