---
name: WWW-GoodData
version: 1.7
author:
  - 'Lubomir Rintel <lkundrak@v3.sk>'
abstract: Client library for GoodData REST-ful API
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-GoodData
  license: http://dev.perl.org/licenses/
  repository: https://github.com/lkundrak/www-gooddata
build_requires:
  JSON: 0
  Test::Pod: 0
requires:
  Getopt::Long: 2.36
  IO::Socket::SSL: 0
  JSON: 0
  LWP::UserAgent: 0
  Pod::Usage: 0
  Text::ParseWords: 0
configure_requires:
  Module::Build: 0.35
provides:
  LWP::Authen::Gooddata:
    file: lib/LWP/Authen/Gooddata.pm
  WWW::GoodData:
    file: lib/WWW/GoodData.pm
  WWW::GoodData::Agent:
    file: lib/WWW/GoodData/Agent.pm
    version: 1.0
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
